name: Deploy Sphinx docs to GitHub Pages

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          cd docs
          pip install -r requirements.txt

      - name: Sphinx build
        run: |
          cd docs
          make html
    
      - name: ghp-import
        run: |
           ghp-import -n -p -f docs/_build/html
    

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true